# Generated by Django 5.0.4 on 2025-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgnify_bgcs", "0006_umaptransform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="umaptransform",
            name="model_file",
        ),
        migrations.AddField(
            model_name="umaptransform",
            name="model_blob",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
