---
title: "Home Page"
# author: "Santiago Sanchez"
date: "2024-09-04"
number-sections: false
# output: html_document
---


The Home Page serves as the primary navigation hub for the **MGnify Biosynthetic Gene Clusters**. This page provides quick access to the main functionalities of the portal, allowing users to search for BGCs, access API documentation, find user guides, and learn more about the project.

## Keyword search

At the top of every page, you will find the **Keyword Search** bar. This feature allows you to quickly perform a basic search across the portal data and documents using specific keywords or accessions.
This functionality is designed to provide a fast and straightforward way to retrieve data without requiring advanced search criteria.

## Access and explore options

The Home Page offers several options to access and explore metagenomic BGC data:

**Explore BGCs** gives access to more detailed searches using advanced criteria. This feature is particularly useful for users who need to perform complex queries or refine their search results based on specific parameters. Also provides basic statistics on the data portal alongside the detailed results of their searches.

**API Access** section provides documentation for users who wish to programmatically interact with the portal. Review the documentation, which includes endpoint descriptions and parameter details.

**User Documentation** section is where you will find guides on how to use the portal.

**About** section provides background information on the portal and the team behind its development.

This page is access point to exploring and utilising the **MGnify Biosynthetic Gene Clusters** portal.
