# Generated by Django 3.2.25 on 2024-08-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('assembly_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bgcdb_id', models.IntegerField(unique=True)),
                ('true_id', models.BooleanField(blank=True, null=True)),
                ('accession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'assembly',
            },
        ),
        migrations.CreateModel(
            name='BgcClass',
            fields=[
                ('bgc_class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_class_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bgc_class',
            },
        ),
        migrations.CreateModel(
            name='BgcDetector',
            fields=[
                ('bgc_detector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_detector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bgc_detector',
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('biome_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lineage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'biome',
            },
        ),
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('mgyc', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bgcdb_id', models.IntegerField(unique=True)),
                ('contig_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('contig_length', models.IntegerField(blank=True, null=True)),
                ('true_id', models.BooleanField(blank=True, null=True)),
                ('sequence', models.TextField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.assembly')),
            ],
            options={
                'db_table': 'contig',
            },
        ),
        migrations.CreateModel(
            name='FileMd5',
            fields=[
                ('file_md5_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_md5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'file_md5',
            },
        ),
        migrations.CreateModel(
            name='GeneCaller',
            fields=[
                ('gene_caller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gene_caller', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gene_caller',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('mgyp', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_representative', models.CharField(blank=True, max_length=255, null=True)),
                ('pfam', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.IntegerField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'study',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('bgcdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('true_id', models.BooleanField(blank=True, null=True)),
                ('start_position', models.IntegerField(blank=True, null=True)),
                ('end_position', models.IntegerField(blank=True, null=True)),
                ('strand', models.IntegerField(blank=True, null=True)),
                ('protein_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline_version', models.CharField(max_length=255)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.assembly')),
                ('gene_caller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.genecaller')),
                ('mgyc', models.ForeignKey(db_column='mgyc', on_delete=django.db.models.deletion.DO_NOTHING, to='api.contig')),
                ('mgyp', models.ForeignKey(db_column='mgyp', on_delete=django.db.models.deletion.DO_NOTHING, to='api.protein')),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='Bgc',
            fields=[
                ('mgyb', models.IntegerField(primary_key=True, serialize=False)),
                ('bgc_identifier', models.CharField(max_length=255)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('bgc_metadata', models.TextField(blank=True, null=True)),
                ('partial', models.IntegerField(blank=True, null=True)),
                ('bgc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bgcclass')),
                ('bgc_detector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bgcdetector')),
                ('mgyc', models.ForeignKey(blank=True, db_column='mgyc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.contig')),
            ],
            options={
                'db_table': 'bgc',
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='biome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.biome'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.study'),
        ),
    ]
