# Generated by Django 5.0.4 on 2026-03-27 09:26

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mgnify_bgcs', '0019_assembly_genome_quality_assembly_genome_size_mb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeScore',
            fields=[
                ('assembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='genome_score', serialize=False, to='mgnify_bgcs.assembly')),
                ('bgc_count', models.IntegerField(default=0)),
                ('bgc_diversity_score', models.FloatField(default=0.0)),
                ('bgc_novelty_score', models.FloatField(default=0.0)),
                ('bgc_density', models.FloatField(default=0.0)),
                ('taxonomic_novelty', models.FloatField(default=0.0)),
                ('genome_quality', models.FloatField(default=0.0)),
                ('l1_class_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('member_count', models.IntegerField(default=0)),
                ('known_chemistry_annotation', models.CharField(blank=True, max_length=255, null=True)),
                ('mibig_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_bgc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_gcf', to='mgnify_bgcs.bgc')),
            ],
            options={
                'verbose_name': 'GCF',
                'verbose_name_plural': 'GCFs',
            },
        ),
        migrations.CreateModel(
            name='BgcScore',
            fields=[
                ('bgc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bgc_score', serialize=False, to='mgnify_bgcs.bgc')),
                ('novelty_score', models.FloatField(default=0.0)),
                ('domain_novelty', models.FloatField(default=0.0)),
                ('nearest_mibig_accession', models.CharField(blank=True, max_length=50, null=True)),
                ('nearest_mibig_distance', models.FloatField(blank=True, null=True)),
                ('size_kb', models.FloatField(default=0.0)),
                ('classification_l1', models.CharField(blank=True, default='', max_length=100)),
                ('classification_l2', models.CharField(blank=True, max_length=100, null=True)),
                ('classification_l3', models.CharField(blank=True, max_length=100, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('gcf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgc_scores', to='discovery.gcf')),
            ],
        ),
        migrations.CreateModel(
            name='GCFMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance_to_representative', models.FloatField(default=0.0)),
                ('bgc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcf_membership', to='mgnify_bgcs.bgc')),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='discovery.gcf')),
            ],
            options={
                'verbose_name': 'GCF membership',
                'verbose_name_plural': 'GCF memberships',
            },
        ),
        migrations.CreateModel(
            name='MibigReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(db_index=True, max_length=50, unique=True)),
                ('compound_name', models.CharField(max_length=255)),
                ('bgc_class', models.CharField(max_length=100)),
                ('umap_x', models.FloatField()),
                ('umap_y', models.FloatField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('bgc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mibig_ref', to='mgnify_bgcs.bgc')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=512, fields=['embedding'], m=16, name='mibig_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='NaturalProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.TextField()),
                ('chemical_class_l1', models.CharField(max_length=100)),
                ('chemical_class_l2', models.CharField(blank=True, max_length=100, null=True)),
                ('chemical_class_l3', models.CharField(blank=True, max_length=100, null=True)),
                ('structure_svg_base64', models.TextField(blank=True, default='')),
                ('producing_organism', models.CharField(blank=True, max_length=255, null=True)),
                ('bgc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natural_products', to='mgnify_bgcs.bgc')),
            ],
            options={
                'indexes': [models.Index(fields=['chemical_class_l1'], name='idx_np_class_l1'), models.Index(fields=['chemical_class_l1', 'chemical_class_l2'], name='idx_np_class_l1_l2')],
            },
        ),
    ]
