---
title: "Explore BGCs"
# author: "Santiago Sanchez"
date: "2024-08-20"
output: html_document
---


## Advanced Search

The Advanced Search bar allows you to perform fine-grained queries to explore BGC Data Portal. Below is a detailed explanation of each search field and examples of complex search queries to help you utilise this feature effectively.

### Search Fields

- **BGC Class Name**:  
  Enter one or more BGC class names (i.e., alkaloid, nrp, other, polyketide, ripp, saccharide, or terpene) separated by spaces or commas. The search will return BGCs that contain at least one of the specified classes (using an OR logic).

- **MGYB**:  
  Specify a particular MGYB (BGC accession of portal) to directly retrieve data associated with that BGC.

- **Assembly Accession**:  
  Input an ENA assembly accession to find predicted BGCs within that specific assembly.

- **Contig MGYC**:  
  Provide a specific MGYC (contig accession) to locate BGCs within that contig.

- **Biome**:  
  Enter terms related to the biome lineage (e.g., sediment, hydrothermal vent) to filter BGCs that originate from assemblies associated with those biomes.

- **BGC Completeness**:  
  Select from the following options to refine your search based on the BGCs' contig boundaries:
  - **Full-Length BGC**: The BGC is entirely within the contig, meaning both start and end positions are within the boundaries of the contig, indicating a complete prediction.
  - **Single**: Partial BGC (Single edge). The BGC extends to one end of the contig, suggesting that the prediction may be truncated at one side because the contig ends there.
  - **Double**:  Partial BGC (Double edges). The BGC spans the entire length of the contig, indicating that the prediction is likely truncated on both sides, with both ends of the BGC coinciding with the ends of the contig.

- **Pfam**:  
  Enter one or more Pfam accessions (e.g., PF00109, PF00501) separated by spaces or commas. You can define the strategy to search BGCs containing these Pfams:
  - **OR**: The resulting BGCs have at least one of the specified Pfams.
  - **AND**: The resulting BGCs must include all specified Pfams.

- **Pfam Strategy**:  
  The **Pfam Strategy** field determines how the search will interpret multiple Pfam entries. You have two options:
  
  - **OR Logic**: When you select the OR strategy, the search will return BGCs that contain at least one of the Pfams you specified. This is useful when you are interested in BGCs that have any of a list of potential Pfams, allowing for a broader search. For example, if you enter `PF00109 PF00501` and select OR, the search will return BGCs that contain either PF00109, PF00501, or both.
  
  - **AND Logic**: Selecting the AND strategy will narrow the search results to BGCs that must contain all the Pfams you listed. This is ideal when you are looking for BGCs with a specific combination of Pfams. For example, if you enter `PF00109 PF00501` and choose AND, only those BGCs that contain both PF00109 and PF00501 will be returned.

- **Aggregate Strategy**:  
  The **Aggregate Strategy** determines how BGC regions predicted by different detection tools are combined in the final results. This field is important when you want to either view individual predictions or identify consensus regions supported by multiple tools. There are three strategies to choose from:

  - **Single**:  
    This strategy displays the predictions from each tool separately, even if they overlap. When using this option, you might see multiple entries for the same region if different tools predicted similar but not identical regions. This strategy is useful for comparing how different tools view the same region but does not combine their outputs into a single prediction.

  - **Union**:  
    The Union strategy merges regions where at least one gene overlaps across predictions from different tools. The resulting region will be defined by the outermost start and end positions of these overlapping predictions. This strategy creates a broader region that represents all potential BGCs detected by at least one of the selected tools, providing a more inclusive view of the data. It is useful when you want to ensure that you capture all possible BGCs, even if only partially supported by some tools.

  - **Intersection**:  
    The Intersection strategy is the most stringent. It only includes regions where all the selected detection tools agree. The resulting BGC region will be the longest contiguous sequence that all tools have predicted as a BGC. This strategy is particularly useful when you want high-confidence predictions, as it guarantees that the region is supported by multiple independent tools, reducing the likelihood of false positives.

## Results Table

After conducting a search, the results will be displayed in a paginated table. Below are key components of the results summary and table, along with instructions for downloading and interpreting the data.

### Results Summary

- **Total Number of Aggregated Regions**  
- **Class Distribution plot**
- **BGC Completeness Distribution plot** 

### Explanation of Table Columns

- **MGYB**:  
  The BGC accession (or aggregated accession) for the resulting region.

- **Assembly Accession**:  
  The ENA assembly accession number where the BGC was predicted.

- **Contig MGYC**:  
  The accession of the contig containing the BGC.

- **Start Position**:  
  The start coordinate of the BGC within the contig.

- **End Position**:  
  The end coordinate of the BGC within the contig.

- **Detector Names**:  
  Lists the BGC detectors that contributed to the aggregated prediction.

- **Class Names**:  
  The predicted BGC classes within the aggregated region.

### Downloading Search Results
You can download the search results as a **TSV** file, which can be used in conjunction with the API to retrieve the data locally.

This information will help you explore, interpret, and utilise the data from the BGC Portal effectively.
