apiVersion: v1
kind: Secret
metadata:
  name: bgc-data-portal-secret
  namespace: bgc-data-portal-hl-prod

type: Opaque
stringData:
  DJANGO_SECRET_KEY:     ${DJANGO_SECRET_KEY}
  ADMIN_API_TOKEN:       ${ADMIN_API_TOKEN}
  PROJECT_USER_TOKEN:    ${PROJECT_USER_TOKEN}
  DJANGO_DEBUG:          ${DJANGO_DEBUG}

  POSTGRES_USER:         ${POSTGRES_USER}
  POSTGRES_PASSWORD:     ${POSTGRES_PASSWORD}
  POSTGRES_DB:           ${POSTGRES_DB}
  POSTGRES_PORT:         ${POSTGRES_PORT}
  DATABASE_URL:          ${DATABASE_URL}

  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  CELERY_BROKER_URL:     ${CELERY_BROKER_URL}
  CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}

  FASTAPI_URL:           ${FASTAPI_URL}
  FASTAPI_INTERNAL_URL:  ${FASTAPI_INTERNAL_URL}
  FASTAPI_EXTERNAL_URL:  ${FASTAPI_EXTERNAL_URL}

  DJANGO_CACHE_BACKEND:  ${DJANGO_CACHE_BACKEND}
