---
title: "Getting Started"
# author: "Santiago Sanchez"
date: "2024-08-20"
# output: html_document
---


## Basic Navigation

The **Biosynthetic Gene Cluster (BGC) Portal** is designed with three primary components that help users navigate and utilise its features effectively. Below is an overview of these components:

### 1. Home Page

The Home Page is your entry point to the BGC Portal. Here, you can navigate to different sections of the site, perform a quick keyword search, and access key functionalities. The main features of the Home Page include:

- **Keyword Search**: Located at the top of the page, this allows you to search the portal using specific keywords or accession numbers, retrieving relevant records from both documentation and data. This is equivalent to calling the `GET /api/v1/search/` endpoint of the API.
- **Access and Explore Options**: 
  - **Search BGCs**: Directs you to the Explore BGCs page for more detailed queries.
  - **API Access**: Provides documentation on how to use the API for programmatic access to BGC data.
  - **User Documentation**: Guides and examples to help you navigate and utilise the portal effectively.
  - **About Us**: Information about the project, including details on the EUREMAP initiative supporting marine bioprospecting research.

### 2. Explore BGCs Page

The Explore BGCs Page is where users can perform detailed searches and view the results. It includes:

- **Advanced Search Sidebar**: This allows for complex queries using various criteria, including BGC class names, specific accessions, biome data, and more. This is equivalent to calling the `GET /api/v1/bgcs/` endpoint of the API.
- **Results Table**: Displays the outcomes of your search in a paginated format, with options to download the data in TSV. The table includes key details such as BGC accession, assembly accession, contig information, and detector names. This results are equivalent to the results of calling the `GET /api/v1/search/` or `GET /api/v1/bgcs/`  endpoints of the API.

### 3. BGC Details Page

The BGC Details Page provides an in-depth view of a specific biosynthetic gene cluster. Key features include:

- **Aggregated Region Basic Information**: Displays essential details such as assembly accession, contig information, biome data, and the BGC classes predicted.
- **BGC Plot**: A visual representation of the BGC, including coding regions, Pfam annotations, and predictions from various detectors.
- **CDS Data**: Detailed information about coding sequences, including protein sequences, Pfam descriptions, and links to external resources.
- **Download Options**: Allows you to download data related to the BGC in various formats, including GeneBank, JSON, FASTA, and GFF3. This is equivalent to calling the `GET /api/v1/contig_region/` endpoint of the API using the MGYC and start/end positions of the aggregated region.

## Glossary of Terms

Below are definitions of key terms and concepts used in the BGC Portal:

- **Biosynthetic Gene Cluster (BGC)**: A group of genes that collectively are predicted to produce a secondary metabolite by a specific BGC detector, often with ecological or pharmaceutical significance.
- **Aggregated Region**: In the context of the BGC Portal, an aggregated region refers to a genomic region that is identified as a BGC through the combined predictions of multiple BGC detection tools. The aggregation process involves comparing the predictions from different detectors and merging them based on specific strategies (i.e., single, union, intersection). The resulting aggregated region represents the consensus prediction, which may span across overlapping regions identified by the different tools, ensuring a comprehensive and reliable identification of the BGC.
- **MGYB**: A specific accession number related to each BGC predictions within the portal.
- **Aggregate Strategy**: The method used to combine predictions from multiple BGC detectors. This can be done using single, union, or intersection strategies to determine the final predicted BGC regions.

For more detailed instructions, please refer to the specific sections of the documentation.
